### ISSUE TITLE
when to open source?

### ISSUE THREAD

**Issue by mmhhkk123** [yanmin-wu/EAO-SLAM#1]
您好！听说您的这篇论文已经被IROS接收，不知道是否可以开源一下代码，学习一下

**Comment by yanmin-wu** [comment]
您好，谢谢关注，由于课题组参加 IROS 2020 挑战赛会用到这部分代码，所以预计时间会在今年 IROS 会议召开之后。

**Comment by joshi-bharat** [comment]
Did your paper got accepted? Are you open sourcing the code?

**Comment by yanmin-wu** [comment]
> Did your paper got accepted? Are you open sourcing the code?

We plan to open it in November after the conference.

**Comment by Hao-HUST** [comment]
> > Did your paper got accepted? Are you open sourcing the code?
> 
> We plan to open it in November after the conference.

Will you plan to release the code after November 25?
