### ISSUE TITLE
关于运行其他数据集和真实场景

### ISSUE THREAD

**Issue by yingxinli** [yanmin-wu/EAO-SLAM#10]
感谢大佬您卓越的贡献！我想对您的项目进行研究，请问一下我要在其他TUM数据集上包括真实场景测试的话，应该如何使用，谢谢！

**Comment by yingxinli** [comment]
我猜您的项目要运行其他数据集，可能需要预处理的数据或者设置成在线模式。想问下我需要那些预处理数据或者怎么正确设置在线模式！谢谢！

**Comment by Wang-Minxin** [comment]
请问您有没有成功复习代码，我在Ubuntu18.04和Ubuntu20.04上运行，都出现了段错误（核心已转储）。
ORB-SLAM2 Copyright (C) 2014-2016 Raul Mur-Artal, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: Monocular

Loading ORB Vocabulary. This could take a while...
Vocabulary loaded!

Offline Semantic mode

Camera Parameters: 
- fx: 535.4
- fy: 539.2
- cx: 320.1
- cy: 247.6
- k1: 0
- k2: 0
- p1: 0
- p2: 0
- fps: 30
- color order: RGB (ignored if grayscale)

line detector Parameters: 
- numoctaves: 1
- octaveratio: 2

ORB Extractor Parameters: 
- Number of Features: 1000
- Scale Levels: 8
- Scale Factor: 1.2
- Initial Fast Threshold: 20
- Minimum Fast Threshold: 7
read groundtruth.txt
Offline semi-dense mapping and line segment extraction

-------
Start processing sequence ...
Images in the sequence: 405

updating model
段错误 (核心已转储)

**Comment by yanmin-wu** [comment]
如果是离线模式：
1. object detection 结果，保存成与我一样的格式；
2. 相机初始化那一帧相对地面的旋转角（我这里是读取 groundtruth 中初始帧的位姿来做的），因为假设物体都是平行于地面的；
3. 可能调整数据关联和异常值剔除的策略。
在线模式：
将上面的步骤 1 换成在线目标检测，开辟一个新的线程，与 Tracking 线程并行，将检测结果送入 tracking 线程。

**Comment by yingxinli** [comment]
> 请问您有没有成功复现代码，我在Ubuntu18.04和Ubuntu20.04上运行，都出现了段错误（核心已转储）。 ORB-SLAM2 Copyright (C) 2014-2016 Raul Mur-Artal, University of Zaragoza. This program comes with ABSOLUTELY NO WARRANTY; This is free software, and you are welcome to redistribute it under certain conditions. See LICENSE.txt.
> 
> Input sensor was set to: Monocular
> 
> Loading ORB Vocabulary. This could take a while... Vocabulary loaded!
> 
> Offline Semantic mode
> 
> Camera Parameters:
> 
> * fx: 535.4
> * fy: 539.2
> * cx: 320.1
> * cy: 247.6
> * k1: 0
> * k2: 0
> * p1: 0
> * p2: 0
> * fps: 30
> * color order: RGB (ignored if grayscale)
> 
> line detector Parameters:
> 
> * numoctaves: 1
> * octaveratio: 2
> 
> ORB Extractor Parameters:
> 
> * Number of Features: 1000
> * Scale Levels: 8
> * Scale Factor: 1.2
> * Initial Fast Threshold: 20
> * Minimum Fast Threshold: 7
>   read groundtruth.txt
>   Offline semi-dense mapping and line segment extraction
> 
> Start processing sequence ... Images in the sequence: 405
> 
> updating model 段错误 (核心已转储)

我在ubuntu16.04上复现了代码，你的这个问题我建议可以再ORBSLAM2的issue里面找一找问题原因，也许可以解决。

**Comment by yingxinli** [comment]
> 如果是离线模式：
> 
> 1. object detection 结果，保存成与我一样的格式；
> 2. 相机初始化那一帧相对地面的旋转角（我这里是读取 groundtruth 中初始帧的位姿来做的），因为假设物体都是平行于地面的；
> 3. 可能调整数据关联和异常值剔除的策略。
>    在线模式：
>    将上面的步骤 1 换成在线目标检测，开辟一个新的线程，与 Tracking 线程并行，将检测结果送入 tracking 线程。

感谢回复！谢谢您卓越的工作！

**Comment by yingxinli** [comment]
> 如果是离线模式：
> 
> 1. object detection 结果，保存成与我一样的格式；
> 2. 相机初始化那一帧相对地面的旋转角（我这里是读取 groundtruth 中初始帧的位姿来做的），因为假设物体都是平行于地面的；
> 3. 可能调整数据关联和异常值剔除的策略。
>    在线模式：
>    将上面的步骤 1 换成在线目标检测，开辟一个新的线程，与 Tracking 线程并行，将检测结果送入 tracking 线程。

我想问一下KeyFrameTrajectory.txt保存在哪里呢，我在代码中看到有保存的代码，但是似乎并没有得到。感谢帮助

**Comment by gao-yiliang** [comment]
> > 如果是离线模式：
> > 
> > 1. object detection 结果，保存成与我一样的格式；
> > 2. 相机初始化那一帧相对地面的旋转角（我这里是读取 groundtruth 中初始帧的位姿来做的），因为假设物体都是平行于地面的；
> > 3. 可能调整数据关联和异常值剔除的策略。
> >    在线模式：
> >    将上面的步骤 1 换成在线目标检测，开辟一个新的线程，与 Tracking 线程并行，将检测结果送入 tracking 线程。
> 
> 我想问一下KeyFrameTrajectory.txt保存在哪里呢，我在代码中看到有保存的代码，但是似乎并没有得到。感谢帮助

请问您解决这个问题了吗？我也没有找到KeyFrameTrajectory.txt保存在哪里了。
