### ISSUE TITLE
段错误

### ISSUE THREAD

**Issue by Wang-Minxin** [yanmin-wu/EAO-SLAM#11]
您好，我最近在研究轻量级的语义SLAM算法，在Ubuntu20.04和Ubuntu18.04上运行您的代码，总是出现段错误，代码打印如下：
wmx@wmx:~/EAO-SLAM$ ./Examples/Monocular/mono_tum None  ~/rgbd_dataset_freiburg3_long_office_household/

ORB-SLAM2 Copyright (C) 2014-2016 Raul Mur-Artal, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: Monocular

Loading ORB Vocabulary. This could take a while...
Vocabulary loaded!

Offline Semantic mode

Camera Parameters: 
- fx: 535.4
- fy: 539.2
- cx: 320.1
- cy: 247.6
- k1: 0
- k2: 0
- p1: 0
- p2: 0
- fps: 30
- color order: RGB (ignored if grayscale)

line detector Parameters: 
- numoctaves: 1
- octaveratio: 2

ORB Extractor Parameters: 
- Number of Features: 1000
- Scale Levels: 8
- Scale Factor: 1.2
- Initial Fast Threshold: 20
- Minimum Fast Threshold: 7
read groundtruth.txt
Offline semi-dense mapping and line segment extraction

-------
Start processing sequence ...
Images in the sequence: 405

updating model
段错误 (核心已转储)

我不知道怎么去解决这个问题，请您不吝赐教。谢谢！

**Comment by pengxinyi-up** [comment]
请问解决了，我也是，调整ulimit好像也没什么用

**Comment by yanmin-wu** [comment]
你可以试试将所有 CMakeLists.txt （包括第三方库）中的 -march=native 删掉，重新编译试试。

**Comment by pengxinyi-up** [comment]
> 
> 
> 你可以试试将所有 CMakeLists.txt （包括第三方库）中的 -march=native 删掉，重新编译试试。

非常感谢作者的回复，亲测有效，可以顺利运行完了

**Comment by Wang-Minxin** [comment]
非常感谢，我已经顺利运行成功！

**Comment by BloodLemonS** [comment]
> 非常感谢，我已经顺利运行成功！

你好我问一下，我也按照这里面说的删掉了所有的-match=native，比较之前能够运行一会，但是并不能完全运行完，运行一段时间以后就会出现下面的错误，我把段错误打印出来问题是这样的应该怎么解决？
Stack trace (most recent call last) in thread 1314:
#7    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#6    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f16a69a461e, in clone
#5    Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7f16a89186da, in 
#4    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f16a6f604bf, in 
#3    Object "/home/lemon/EAO-SLAM/lib/libORB_SLAM2.so", at 0x7f16a8467e45, in ORB_SLAM2::LocalMapping::Run()
#2    Object "/home/lemon/EAO-SLAM/lib/libORB_SLAM2.so", at 0x7f16a8467259, in ORB_SLAM2::LocalMapping::MergePotentialAssObjs()
#1    Object "/home/lemon/EAO-SLAM/lib/libORB_SLAM2.so", at 0x7f16a85af9d7, in ORB_SLAM2::Object_Map::WhetherMergeTwoMapObjs(ORB_SLAM2::Map*)
#0    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f16a6f4bd33, in std::_Rb_tree_increment(std::_Rb_tree_node_base*)
段错误 (地址没有映射到对象 [0xa1])
段错误 (核心已转储)

**Comment by xinzhichao** [comment]
> 

您好，请问解决了吗，我也是这个问题

**Comment by xinzhichao** [comment]
> > 非常感谢，我已经顺利运行成功！
> 
> 你好我问一下，我也按照这里面说的删掉了所有的-match=native，比较之前能够运行一会，但是并不能完全运行完，运行一段时间以后就会出现下面的错误，我把段错误打印出来问题是这样的应该怎么解决？ Stack trace (most recent call last) in thread 1314: #7 Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in #6 Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f16a69a461e, in clone #5 Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7f16a89186da, in #4 Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f16a6f604bf, in #3 Object "/home/lemon/EAO-SLAM/lib/libORB_SLAM2.so", at 0x7f16a8467e45, in ORB_SLAM2::LocalMapping::Run() #2 Object "/home/lemon/EAO-SLAM/lib/libORB_SLAM2.so", at 0x7f16a8467259, in ORB_SLAM2::LocalMapping::MergePotentialAssObjs() #1 Object "/home/lemon/EAO-SLAM/lib/libORB_SLAM2.so", at 0x7f16a85af9d7, in ORB_SLAM2::Object_Map::WhetherMergeTwoMapObjs(ORB_SLAM2::Map*) #0 Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f16a6f4bd33, in std::_Rb_tree_increment(std::_Rb_tree_node_base*) 段错误 (地址没有映射到对象 [0xa1]) 段错误 (核心已转储)

您好，请问解决了吗，我也是这个问题

**Comment by zzzzq-0000** [comment]
> 

您好，请问解决了么，我也是这个问题

**Comment by MrAltria** [comment]
感谢，已经成功运行！

**Comment by ljjTYJR** [comment]
https://github.com/RainerKuemmerle/g2o/pull/314
https://github.com/raulmur/ORB_SLAM2/pull/844
