### ISSUE TITLE
Ground truth odometry measurement in data not matching number of object detection measurement. 

### ISSUE THREAD

**Issue by dishank-b** [yanmin-wu/EAO-SLAM#12]
In the folder `data`, the total number of ground truth odometry is given is around `~8700` whereas the number of object detection given is for total `~2585` number of frames. 

I want to implement the similar of your code where I use the ground truth odometry, but since odometry measurement frequency seems to be much more than object detection measurement frequency, I am not sure how to map the two? 

Can you help with this? Thank you

**Comment by yanmin-wu** [comment]
The ground truth is collected at a high frequency of around 100 fps, while the images (as well as the object detection) are captured at a low frequency of around 30 fps, resulting in an N-to-1 correspondence. As illustrated below, I index the image by timestamps of the Groundtruth. [Example code](https://github.com/yanmin-wu/EAO-SLAM/blob/master/src/Tracking.cc#L509).
![timestamp](https://user-images.githubusercontent.com/52712492/135559684-edda606f-8118-40d0-808e-d00237c71b90.png)

**Comment by dishank-b** [comment]
okay, thank you. 
Also, the pose given in ground truth odomtery, are the values are in the global frame or is it current pose in the frame of the previous pose?

**Comment by yanmin-wu** [comment]
The global frame.
