### ISSUE TITLE
运行自己制作的数据集或其他数据集groundtruth该如何获取？

### ISSUE THREAD

**Issue by pansyl** [yanmin-wu/EAO-SLAM#13]
如题，请问我在运行自己用kinetcv2制作的数据集，但kinectv2并不会提供groundtruth文件，而代码需要读取groundtruth，请问您我该如何进一步正确使用代码，或者如何获取这个groundtruth.txt呢。或者其他没有真实轨迹的数据集也是一样，感谢您的帮助！

**Comment by yanmin-wu** [comment]
读取 groundtruth 的目的并不是获得每一帧的真值，**只需要初始化的第一帧相对地面的旋转角**，因为假设物体都是平行于地面的，本质上只使用了初始帧的 roll 和 pitch 角度（代码：[L1018](https://github.com/yanmin-wu/EAO-SLAM/blob/master/src/Tracking.cc#L1018)-[L1045](https://github.com/yanmin-wu/EAO-SLAM/blob/master/src/Tracking.cc#L1045)）。
所以自己录制数据集只需要保证平行于地面初始化即可，读取 groundtruth 的相关代码可以注释掉。其他没有 groundtruth 的数据集需要自己估计一下初始帧相对地面的 roll 和 pitch（比如 IMU 提供重力方向，或者平面估计）。

**Comment by yingxinli** [comment]
好的，感谢帮助！ 我已成功运行！
