### ISSUE TITLE
Joint Optimization

### ISSUE THREAD

**Issue by Be997398715** [yanmin-wu/EAO-SLAM#14]
Hi, when I checking your code in Optimizer.cc, I didn't find the expression in the paper - 'we then jointly optimize object and camera poses'. I want to know where the 'optimize object' add, hope for your reply, this will help me learn your code better.

**Comment by yanmin-wu** [comment]
This version did not include the optimization part. We reference the code of CubeSLAM. [Optimizer.cc](https://github.com/shichaoy/cube_slam/blob/master/orb_object_slam/src/Optimizer.cc), [g2o_Object.cpp](https://github.com/shichaoy/cube_slam/blob/master/orb_object_slam/src/g2o_Object.cpp)

**Comment by Be997398715** [comment]
> This version did not include the optimization part. We reference the code of CubeSLAM. [Optimizer.cc](https://github.com/shichaoy/cube_slam/blob/master/orb_object_slam/src/Optimizer.cc), [g2o_Object.cpp](https://github.com/shichaoy/cube_slam/blob/master/orb_object_slam/src/g2o_Object.cpp)

Thanks for your reply.
