### ISSUE TITLE
build.sh报错

### ISSUE THREAD

**Issue by QingWind6** [yanmin-wu/EAO-SLAM#15]
想复现大佬的代码，build项目过程中报错如下：
①/EAO-SLAM/include/YOLOv3SE.h:164:38: error: no matching function for call to ‘_IplImage::_IplImage(cv::Mat&)’
   IplImage* iplimg = new IplImage(img);
②EAO-SLAM/Thirdparty/Line3Dpp/serialization.h:62:18: error: ‘cout’ is not a member of ‘std’
             std::cout << "[L3D++] serializeFromFileArchive(): File '" << file << "'' could not be opened " << std::endl;

麻烦大佬可以帮忙看下哪里出错了，谢谢

**Comment by QingWind6** [comment]
第二个解决了，头文件include<iostream>就可以了，但是第一个问题依旧没有解决

**Comment by yanmin-wu** [comment]
目测是 opencv 的问题，确定 opencv 是否配置好了，还有版本。

**Comment by QingWind6** [comment]
opencv的版本没问题哈哈，谢谢作者回复啦！刚刚问题都解决了，一开始也以为是openCV版本问题，查了一下没啥问题，后面包含了一些头文件顺利跑通，不过跑到一半还是报核心已转储，不知道是不是我电脑内存问题

**Comment by YOHO666999** [comment]
你好，第一个问题怎莫解决的呀
