### ISSUE TITLE
terminate called after throwing an instance of 'cv::Exception

### ISSUE THREAD

**Issue by trti-llro** [yanmin-wu/EAO-SLAM#16]
1311867723.609219
1311867723.641284
1311867723.677183
New Map created with 108 points
OpenCV Error: Assertion failed ((type == (((5) & ((1 << 3) - 1)) + (((1)-1) << 3)) || type == (((6) & ((1 << 3) - 1)) + (((1)-1) << 3)) || type == (((5) & ((1 << 3) - 1)) + (((2)-1) << 3)) || type == (((6) & ((1 << 3) - 1)) + (((2)-1) << 3)))) in gemm, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/core/src/matmul.cpp, line 1558
terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/core/src/matmul.cpp:1558: error: (-215) (type == (((5) & ((1 << 3) - 1)) + (((1)-1) << 3)) || type == (((6) & ((1 << 3) - 1)) + (((1)-1) << 3)) || type == (((5) & ((1 << 3) - 1)) + (((2)-1) << 3)) || type == (((6) & ((1 << 3) - 1)) + (((2)-1) << 3))) in function gemm

你好，我最近在自己的数据集上做实验，把yolo离线数据、tum_mono内参替换成了自己的，groundtruth.txt文件没动，但是连续跑几十帧以后就会报这个错误，想请问一下这个可能是哪里的问题？

**Comment by yanmin-wu** [comment]
你这是初始化之后报错的，初始化之后需要读取初始帧的 groundtruth 位姿，根据时间戳来读取的，你用的自己的数据，可能图像的时间戳没有在 groundtruth.txt 中找到，你看看 mInitialFrame.mGroundtruthPose_mat 是不是没有数据？
