### ISSUE TITLE
object map初始化的条件

### ISSUE THREAD

**Issue by TINY-KE** [yanmin-wu/EAO-SLAM#17]
感谢您的工作。在阅读代码过程中，有几个问题想请教：
请问，为什么object map的初始化，要满足mCurrentFrame.mnId > mInitialSecendFrame.mnId？
当前帧（mCurrentFrame）的ID，大于初始帧（mInitialFrame）的Id 不就行了。

**Comment by yanmin-wu** [comment]
> 
在 ORB-SLAM 中，只有连续两帧的特征点数都大于100个时，才会进行初始化。如果仅创建了第一帧 mInitialFrame，
其下一帧不满足要求，则会重新创建一个新的 mInitialFrame。其实也就是要保证点云 map 创建好了再初始化 object map。
