### ISSUE TITLE
libYOLOv3SE.so

### ISSUE THREAD

**Issue by Wang-Minxin** [yanmin-wu/EAO-SLAM#18]
作者，您好。我最近想基于Yolov3SE.h添加在线目标检测功能，但是由于我的电脑没有显卡未能生成libYOLOv3SE.so文件。请问这个库文件能否方便分享一下，谢谢。

**Comment by Wang-Minxin** [comment]
谢谢，我修改了yolov3_SpringEdition的代码，去掉了其中使用cuda的代码，现在已经能够在线而非实时的目标检测了。

**Comment by nufddvv** [comment]
想问一下重新编译生成的库文件是在什么架构上，我用的Jeston Nano 貌似不支持用源代码生成libYOLOv3SE.so @Wang-Minxin
