### ISSUE TITLE
the version of g++

### ISSUE THREAD

**Issue by Tineey** [yanmin-wu/EAO-SLAM#8]
Hi, I met some problems as shown in pictures when I was compiling the code.
I think maybe they are related to the version of g++? My g++ version is 4.8.4. Could you please tell me the version of g++? or how to solve these problems? thanks very much!!
![81201625704756_ pic](https://user-images.githubusercontent.com/31068269/124851929-73adca80-df71-11eb-8265-6b86c5016e4c.jpg)
![81801625708422_ pic](https://user-images.githubusercontent.com/31068269/124851959-80cab980-df71-11eb-9251-e10445b6af1c.jpg)

**Comment by yanmin-wu** [comment]
Apologies for not encountering this error. 5.4.0 is the version I'm using.
