### ISSUE TITLE
Line3dpp error

### ISSUE THREAD

**Issue by poetgeorge** [yanmin-wu/EAO-SLAM#9]
I run this project on my ubuntu 20.04 with opencv 4.5.1 and eigen 3.3.9. I had already fix many errors, now I can get sparse object map and semi-dense point clouds, but failed in Line3dpp part cause of "double free or corruption (out)"

**Comment by yanmin-wu** [comment]
Line3dpp is a part of [semidense-lines](https://github.com/shidahe/semidense-lines); did you successfully run it?
